### ISSUE TITLE
Where's the code for swagger-explained?

### ISSUE THREAD

**Issue by jpuck** [bfanger/bfanger.github.io#2]
This is not really an issue per se, but I noticed you host https://bfanger.nl/swagger-explained/ (which is awesome) from this repository, and I wanted to ask you how? I was going to submit a PR for some tiny fixes, but I couldn't figure out where the code was. I see the homepage code, and the `x-github-request-id` response header, so I assume I'm in the right place, but can't quite figure it out.

Thanks!

**Comment by bfanger** [comment]
https://github.com/bfanger/swagger-explained

Looking forward to the PR

**Comment by jpuck** [comment]
Ah I see, it's a separate project and you have an organization page setup. Thanks, I submitted a tiny typo fix.
